config/routes.rb
Impdates::Application.routes.draw do
  resources :impdates
  root :to => "impdates#index"

end

app/models/impdate.rb
class Impdate < ActiveRecord::Base
  attr_accessible :explanation, :impdate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/impdates_controller.rb
class ImpdatesController < ApplicationController
  # GET /impdates
  # GET /impdates.json
  def index
    @impdates = Impdate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @impdates }
    end
  end

  # GET /impdates/1
  # GET /impdates/1.json
  def show
    @impdate = Impdate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @impdate }
    end
  end

  # GET /impdates/new
  # GET /impdates/new.json
  def new
    @impdate = Impdate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @impdate }
    end
  end

  # GET /impdates/1/edit
  def edit
    @impdate = Impdate.find(params[:id])
  end

  # POST /impdates
  # POST /impdates.json
  def create
    @impdate = Impdate.new(params[:impdate])

    respond_to do |format|
      if @impdate.save
        format.html { redirect_to @impdate, notice: 'Impdate was successfully created.' }
        format.json { render json: @impdate, status: :created, location: @impdate }
      else
        format.html { render action: "new" }
        format.json { render json: @impdate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /impdates/1
  # PUT /impdates/1.json
  def update
    @impdate = Impdate.find(params[:id])

    respond_to do |format|
      if @impdate.update_attributes(params[:impdate])
        format.html { redirect_to @impdate, notice: 'Impdate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @impdate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /impdates/1
  # DELETE /impdates/1.json
  def destroy
    @impdate = Impdate.find(params[:id])
    @impdate.destroy

    respond_to do |format|
      format.html { redirect_to impdates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/impdates_helper.rb
module ImpdatesHelper
end

app/views/impdates/_form.html.erb
<%= form_for(@impdate) do |f| %>
  <% if @impdate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@impdate.errors.count, "error") %> prohibited this impdate from being saved:</h2>

      <ul>
      <% @impdate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :important_date %><br />
    <%= f.date_select :impdate %>
  </div>
  <div class="field">
    <%= f.label :justification_of_importance %><br />
    <%= f.text_field :explanation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/impdates/edit.html.erb
<h1>Editing impdate</h1>

<%= render 'form' %>

<%= link_to 'Show', @impdate %> |
<%= link_to 'Back', impdates_path %>

app/views/impdates/index.html.erb
<h1>Important Dates</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Justification of Importance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<% @impdates.each do |impdate| %>
  <tr>
  <% if impdate.impdate > Date.today %>
    <td><%= impdate.impdate %></td>
    <td><%= impdate.explanation %></td>
    <td><%= link_to 'Show', impdate %></td>
    <td><%= link_to 'Edit', edit_impdate_path(impdate) %></td>
    <td><%= link_to 'Destroy', impdate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Important Date', new_impdate_path %>

app/views/impdates/new.html.erb
<h1>New impdate</h1>

<%= render 'form' %>

<%= link_to 'Back', impdates_path %>

app/views/impdates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Impdate:</b>
  <%= @impdate.impdate %>
</p>

<p>
  <b>Explanation:</b>
  <%= @impdate.explanation %>
</p>


<%= link_to 'Edit', edit_impdate_path(@impdate) %> |
<%= link_to 'Back', impdates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Important Dates</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>